import { FormEvent, useState } from 'react'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { useLanguage } from '../context/LanguageContext'
type Status = 'idle' | 'submitting' | 'success' | 'error' | 'unconfigured'
export function ContactForm() {
  const { t } = useLanguage(); const [status, setStatus] = useState<Status>('idle'); const [errors, setErrors] = useState<Record<string, string>>({})
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const next: Record<string, string> = {}; const name = String(form.get('name') || '').trim(); const email = String(form.get('email') || '').trim(); const message = String(form.get('message') || '').trim(); if (!name) next.name = t('required'); if (!/^\S+@\S+\.\S+$/.test(email)) next.email = !email ? t('required') : t('invalidEmail'); if (!message) next.message = t('required'); setErrors(next); if (Object.keys(next).length) return; const endpoint = import.meta.env.VITE_FORMSPREE_ENDPOINT; if (!endpoint) { setStatus('unconfigured'); return } try { setStatus('submitting'); const response = await fetch(endpoint, { method: 'POST', body: form, headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('Request failed'); setStatus('success'); event.currentTarget.reset() } catch { setStatus('error') } }
  return <form className="contact-form" onSubmit={submit} noValidate><div className="form-grid"><label>{t('name')}<input name="name" autoComplete="name" aria-invalid={Boolean(errors.name)} />{errors.name && <small>{errors.name}</small>}</label><label>{t('email')}<input type="email" name="email" autoComplete="email" aria-invalid={Boolean(errors.email)} />{errors.email && <small>{errors.email}</small>}</label></div><label>{t('subject')}<input name="subject" /></label><label>{t('message')}<textarea name="message" rows={5} aria-invalid={Boolean(errors.message)} />{errors.message && <small>{errors.message}</small>}</label><button className="button button--dark" disabled={status === 'submitting'}>{status === 'submitting' ? t('sending') : <>{t('send')} <ArrowRight size={17} /></>}</button>{status === 'success' && <p className="form-message form-message--success"><CheckCircle2 size={17} />{t('success')}</p>}{status === 'error' && <p className="form-message">{t('error')}</p>}{status === 'unconfigured' && <p className="form-message">{t('configured')} <a href="mailto:odriozolageronimo@gmail.com">odriozolageronimo@gmail.com</a></p>}</form>
}
